// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txyerrwezxrtpqnllpxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4eWVycndlenhydHBxbmxscHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNTk2NTEsImV4cCI6MjA3NjYzNTY1MX0.eI-j3TRD5u9JVMG5bB3Zn4oKbTkoMHPj84UMmRp_ZOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});